### ISSUE TITLE
Issue with example

### ISSUE THREAD

**Issue by tyvdh** [cloudflare/dog#21]
Running a local version of dog via the README.

Based off the error message I'm not really sure what's going on.

```bash
% node -v
v16.15.0

% miniflare --version
2.5.0

% pnpm --version
7.2.1
```

```bash
[mf:err] GET /ws?u=tyler: TypeMismatchError: The data argument must be an integer-type TypedArray
    at Crypto.getRandomValues (node:internal/crypto/random:317:11)
    at Crypto.getRandomValues (node:internal/crypto/webcrypto:704:10)
    at DurableObjectNamespace.newUniqueId (/Users/tylervanderhoeven/Desktop/dog/node_modules/.pnpm/@miniflare+durable-objects@2.3.0/node_modules/@miniflare/durable-objects/src/namespace.ts:211:15)
    at Lobby.clusterize (/Users/tylervanderhoeven/Desktop/dog/example/build/index.js:385:19)
    at Lobby.#identify (/Users/tylervanderhoeven/Desktop/dog/example/build/index.js:420:27)
    at Lobby.fetch (/Users/tylervanderhoeven/Desktop/dog/example/build/index.js:401:30)
    at /Users/tylervanderhoeven/Desktop/dog/node_modules/.pnpm/@miniflare+durable-objects@2.3.0/node_modules/@miniflare/durable-objects/src/namespace.ts:93:25
    at AsyncLocalStorage.run (node:async_hooks:327:14)
    at InputGate.runWith (/Users/tylervanderhoeven/Desktop/dog/node_modules/.pnpm/@miniflare+shared@2.3.0/node_modules/@miniflare/shared/src/sync/gate.ts:71:29)
GET /ws?u=tyler 500 Internal Server Error (23.57ms)
[mf:err] TypeError: Web Socket request did not return status 101 Switching Protocols response with Web Socket
    at Server.<anonymous> (/Users/tylervanderhoeven/Desktop/dog/node_modules/.pnpm/@miniflare+http-server@2.3.0/node_modules/@miniflare/http-server/src/index.ts:383:11)
```

**Comment by tyvdh** [comment]
Updated dependencies and ran `pnpm i` and we seem to be working now.
